### ISSUE TITLE
Clarify that PostgreSQL must be installed for `pg` gem to bundle properly

### ISSUE THREAD

**Issue by jeffbyrnes** [redhotvengeance/deep_thought#7]
Had a bit of confusion when I tried to bundle initially, until I realized that the `pg` gem needs an actual install of Postgres to install against.

Might be helpful to clue in users more explicitly that this is the case. For Mac users, encouraging them to `brew install postgresql` is likely enough.

**Comment by redhotvengeance** [comment]
With #2, support for multiple database types was added. In light of this issue you opened, I'm considering moving `pg` to just a development dependency (for those who are hacking on Deep Thought itself, rather than just using it). Of course, that means users will need to declare the appropriate database gem in their personal Deep Thought installations.

Thoughts on this?

**Comment by jeffbyrnes** [comment]
@redhotvengeance that sounds sane to me, in light of the fact that someone using MySQL wouldn't use the `pg` gem at all.

In either case, just needs to be well-documented what's required to `bundle` & generate the lockfile needed for Heroku.

**Comment by jeffbyrnes** [comment]
I'm going through old issues of mine that are still open & closing them out.
